---
- name: Setup web servers and deploy Flipkart clone
  hosts: webservers
  become: true
  connection: ssh
  tasks:

    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Install git
      ansible.builtin.yum:
        name: git
        state: present

    - name: Ensure /home/ansible directory exists
      ansible.builtin.file:
        path: /home/ansible
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Ensure Ansible-Playbook directory exists
      ansible.builtin.file:
        path: /home/ansible/Ansible-Playbook
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Clone the Git repository into /home/ansible/Ansible-Playbook
      ansible.builtin.git:
        repo: https://github.com/Msocial123/Flipkart-Clone.git
        dest: /home/ansible/Ansible-Playbook
        version: main
        force: yes
      become_user: ansible

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
