---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:

    - name: install the java 
      action: yum pkg=java-23-amazon-corretto state=present
      ignore_errors: yes

    - name: install the python
      action: yum pkg=python3 state=present  

    - name: install the webservers
      action: yum pkg=httpd state=present  

    - name: install the mariadb-server
      action: yum pkg=mariadb-10.11* state=present

    - name: starting the webservers
      action: service name=httpd state=started

    - name: stoping the webservers
      action: service name=httpd state=stopped

    - name: restarting the webservers
      action: service name=httpd state=restarted 

    - name: starting the mariadb-server
      action: service name=mariadb-server state=started

    - name: stoping the mariadb-server
      action: service name=mariadb-server state=stopped

    - name: restarting the mariadb-server
      action: service name=mariadb-server state=restarted   