---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:

    - name: install the java 
      action: yum pkg=java-23-amazon-corretto state=present
      ignore_errors: yes

    - name: install the python
      action: yum pkg=python3 state=present  

    - name: install the webservers
      action: yum pkg=httpd state=present  

    - name: install the mysqlserver
      action: yum pkg=mysql-server state=present

    - name: starting the webservers
      action: service name=httpd state=started

    - name: stoping the webservers
      action: service name=httpd state=stopped

    - name: restarting the webservers
      action: service name=httpd state=restarted 

    - name: starting the sqlservers
      action: service name=mysqlserver state=started

    - name: stoping the sqlservers
      action: service name=mysqlserver state=stopped

    - name: restarting the sqlservers
      action: service name=mysqlserver state=restarted   