---
- name: Setup web server and deploy Flipkart clone
  hosts: webservers
  become: true
  connection: ssh
  tasks:

    - name: git install
      yum:
        name: git
        state: present

    - name: clone git repository
      git: 
        repo: https://github.com/Msocial123/Flipkart-Clone.git
        dest: /home/ansible/Flipkart-Clone
        version: main
        force: yes

    - name: copy application
      copy:
        src: https://github.com/Msocial123/Flipkart-Clone.git
        dest: /home/ansible/Flipkart-Clone
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: set permission
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes

    - name: ensure httpd
      service:
        name: httpd
        state: stated
        enabled: yes

