---
- hosts: webservers
  become: true
  connection: ssh
  tasks:

    - name: install
      yum:
       name:
         -git
         -httpd
       state: present

    - name: ensure httpd
      service:
        name: httpd
        state: stated
        enabled: yes

    - name: clone git repository
      git: 
        repo: "https://github.com/Msocial123/Flipkart-Clone.git"
        dest: "/home/ansible/Flipkart-Clone"
        version: main
        force: yes

    - name: copy application
      copy:
        src: "/home/ansible/Flipkart-Clone"
        dest: "/var/www/html/"
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: set permission
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes

    

