---
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Install OpenJDK 17
      yum:
        name: java-17-amazon-corretto.x86_64
        state: present

    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Enable EPEL repository using amazon-linux-extras
      shell: amazon-linux-extras install epel -y
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins to start on boot
      systemd:
        name: jenkins
        enabled: true

    - name: Wait for Jenkins port 8080 to be available
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass

    - name: Display Jenkins initial admin password
      debug:
        var: jenkinspass.stdout
