---
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Install OpenJDK 17
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Download Jenkins RPM manually
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.440.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Install Jenkins from RPM
      yum:
        name: /tmp/jenkins.rpm
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins to start on boot
      systemd:
        name: jenkins
        enabled: true

    - name: Wait for Jenkins port 8080 to be available
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass

    - name: Display Jenkins initial admin password
      debug:
        var: jenkinspass.stdout
