---
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Install OpenJDK 17
      yum:
        name: java-17-amazon-corretto.x86_64
        state: present

    - name: Add Jenkins repository
      copy:
        dest: /etc/yum.repos.d/jenkins.repo
        content: |
          [jenkins]
          name=Jenkins
          baseurl=https://pkg.jenkins.io/redhat-stable
          gpgcheck=1
          gpgkey=https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
          enabled=1

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Clean yum cache
      command: yum clean all

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins to start on boot
      systemd:
        name: jenkins
        enabled: true
    - name: Wait for Jenkins port 8080 to be available
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass

    - name: Display Jenkins initial admin password
      debug:
        var: jenkinspass.stdout
